### PR TITLE
Enable extension in browser environments

### PR DESCRIPTION
**Pull request by afonsonf**
Hi, in this PR the extension is enabled for web environments such as vscode.dev and github.dev.

This is done by creating a new entrypoint for the extension where only a subset of the features is enabled, namely:
* code highlighting
* code completion
* code definitions navigation

Changed to use npm compile instead of npm watch in extension debugging because to load changes the instance needs to be reload (does not reload automatically) and compile seems to work better and may solve this: https://github.com/tlaplus/vscode-tlaplus/pull/283#issuecomment-1522196174

## References
* https://github.com/tlaplus/vscode-tlaplus/issues/239
* https://code.visualstudio.com/api/extension-guides/web-extensions

### CODE REVIEW

**Comment by afonsonf** [comment]
I will try to fix the not working features this weekend, if I'm not able to do it, I'll clean up the MR to only include the highlighting to not block it to be enabled

**Comment by afonsonf** [comment]
Got it working, it was the document selector, for some reason in the browser it was on not working for enabling the language features, so I changed it to use directly the laguange id strings. Also clean up the MR and removed the refactoring to have less changes

**Review by lemmy — APPROVED** [review]
LGTM

**Comment by lemmy** [comment]
Do we have to separately add the browser-version to the VSCode marketplace?

**Comment by afonsonf** [comment]
I don't think so, we can trigger the nightly release and check it

**Comment by lemmy** [comment]
https://github.com/tlaplus/vscode-tlaplus/actions/runs/4835623773

**Comment by lemmy** [comment]
Works like a charm, nicely done!
Screenshot 2023-04-28 at 4 42 55 PM

**Pull request merged**
