### PR TITLE
Allow command forms for Java options

### PR DESCRIPTION
**Pull request by pfeodrippe**
In order to enhance the classpath + Java options when running TLC, this patch adds a way to mix static content with dynamic ones when setting `CFG_JAVA_OPTIONS`.

The dynamism is inspired by the `$(...)` form from Bash, anything inside these parentheses will be run as a `spawn` command.

The more general use case is to be able to add anything to the TLC options. My particular use case is to be able to add modules on-demand when using VSCode, e.g. when using

```json
{"...": "...",
 "...": "...",

 "tlaplus.java.options": "$(tladeps --tladeps-vscode --tladeps-raw-deps '{io.github.pfeodrippe/tladeps-edn-module {:mvn/version \"0.5.0\", :tladeps/edn-namespaces [\"tla-edn-module.core\"]}}')",

 "...": "...",
 "...": "...",
}
```

the command `tladeps ...` would be run, which would replace itself with its result (we find the form using a very simple regex).

Let me know what you think, hopefully, this is generic enough, but if you want something more specific for the `tladeps` case, I can do it too o/

### CODE REVIEW

**Comment by lemmy** [comment]
Others are welcome to chime in, but what if we allow users to *optionally* specify a custom script for the extension to invoke instead of directly calling Java? In my opinion, this would make the system more flexible and less brittle. For instance, implementing proper error handling with the proposed approach could prove to be quite cumbersome.

**Comment by afonsonf** [comment]
I also think the new entrypoint would be better and the implementation would be less complex than expanding the arguments

As a curiosity, with the current option "tlaplus.java.home" you can already kind of define a custom entrypoint, like in the following print, but its not the intended usage of that option (only works for check model, for repl it tries first to do java -version)

image

**Comment by lemmy** [comment]
> As a curiosity, with the current option "tlaplus.java.home" you can already kind of define a custom entrypoint, like in the following print, but its not the intended usage of that option (only works for check model, for repl it tries first to do java -version)

How about renaming 'tlaplus.java.home' to something like 'tlaplus.binary.path' and consistently invoking both model-checking and the REPL?

**Comment by pfeodrippe** [comment]
Hi Markus and Afonso, thanks for the options, I knew about this home option, but I would like the user to keep using the latest jar with any additional options passed if they want. Not just a binary but a binary plus any options (if I can reuse the tla2tools, then it’s cool), if this can be done in another way (e.g. the new binary option), then I’m in o/

**Comment by pfeodrippe** [comment]
As the command can do anything, it’s the responsibility of the command handler to deal with any errors.

**Comment by pfeodrippe** [comment]
Let me know if I should close this o/

**Comment by lemmy** [comment]
> Not just a binary but a binary plus any options (if I can reuse the tla2tools, then it’s cool), if this can be done in another way (e.g. the new binary option), then I’m in o/

The options could come from "tlaplus.java.options" (renamed to "tlaplus.binary.options" for consistency).

**Comment by pfeodrippe** [comment]
> > Not just a binary but a binary plus any options (if I can reuse the tla2tools, then it’s cool), if this can be done in another way (e.g. the new binary option), then I’m in o/
> 
> The options could come from "tlaplus.java.options" (renamed to "tlaplus.binary.options" for consistency).

Nice, then I will close this, thanks!

**Pull request closed without merging**
