### PR TITLE
Make TLAPS proof step decorators less distractive.

### PR DESCRIPTION
**Pull request by kape1395**

### CODE REVIEW

**Comment by kape1395** [comment]
Closes #314.

Now, the decorators are shown as color-coded icons on the left instead of setting the line background for all the states except the failed ones. The icon and the line background decorate the failed steps.

**Comment by kape1395** [comment]
@lemmy, could you take a look at this?

Also, it would be great if someone could improve those icons I added. Artwork is not my strongest side.

**Comment by klinvill** [comment]
> Also, it would be great if someone could improve those icons I added. Artwork is not my strongest side.

I often will just borrow open-source icons when I need icons. For example, the Google material design icons are available under an apache license: https://fonts.google.com/icons

**Comment by afonsonf** [comment]
Why not use the vscode icons to have better editor consistency and theme support?
https://microsoft.github.io/vscode-codicons/dist/codicon.html

**Comment by lemmy** [comment]
I was about to suggest DALL-E et al., but lets merge abe4277f1e3f7274d787ad2579a56bff6e4c18d0 and do further improvements in a new PR.

**Comment by kape1395** [comment]
@klinvill, @afonsonf. Thanks for the pointers to the icons.
I'm trying to use the vscode built-in icons but had no luck yet.
  - The place where the icon is picked is here: https://github.com/tlaplus/vscode-tlaplus/blob/56daa35a87cb7656281a5ab001fd71b9e72e3a23/src/tlaps.ts#L89
  - I have to specify a path to the icon. The built-in icons are specified with `$(alert)`, see https://code.visualstudio.com/api/references/icons-in-labels, but that is not working with the decorators and the gutter icons.

Maybe you know how to access the path to the built-in icons? I have impression they are font-based, thus there is no path to them. 

The icons mentioned by @klinvill  are available to download as SVG files, https://fonts.google.com/icons, thus can be used after modifying the color in the downloaded file. But in this case, how to attribute the source properly?

**Pull request merged**
